import random

print(random.randint(5, 20))  # line 1
print(random.randrange(3, 10, 2))  # line 2
print(random.uniform(2.5, 5.5))  # line 3

#Answer
# 1.  Smallest : 5 , Largest : 20
# 2. smallest is 3, largest is 9 . And since the step size is 2. Therefore, 4 could not have been produced by line 2.
# 3. Line 3 uses the random.uniform() function to generate a random floating-point number between 2.5 and 5.5, inclusive. The specific value produced by this line of code could vary each time it is run, but it will always be a float between 2.5 and 5.5.
#The smallest number that could be generated by random.uniform(2.5, 5.5) is 2.5, and the largest number that could be generated is 5.5.

print(random.randint(1, 100))


